-- Make every todo belong to a user

-- 1) Delete orphan TODOs where user_id is NULL
DELETE FROM todos WHERE user_id IS NULL;

-- 2) Drop the existing foreign key constraint (name autogenerated by postgres)
ALTER TABLE todos
DROP CONSTRAINT IF EXISTS todos_user_id_fkey;

-- 3) Enforce NOT NULL
ALTER TABLE todos
ALTER COLUMN user_id SET NOT NULL;

-- 4) Recreate foreign key with desired delete behavior
ALTER TABLE todos
ADD CONSTRAINT todos_user_id_fkey
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
